#pragma once

#include "ofMain.h"
#include "ofxGui.h"

#define GRID_DIV 4

/*
 * for collision detection :
 * if (distance(x center, x line) < radius) then intersect 
 */

struct point
{
	point(float _x, float _y, const int _r, const int _g, const int _b) : x(_x), y(_y), r(_r), g(_g), b(_b) {}

	//Position
	float x;
	float y;

	//Velocity
	float vx = 0;
	float vy = 0;

	//Color
	const int r;
	const int g;
	const int b;

	int gridId = -1;

	void draw() const
	{
		ofSetColor(r, g, b, 100); //set particle color + some alpha
		ofDrawCircle(x, y, 2.0F); //draw a point at x,y coordinates, the size of a 2 pixels
	}
};

struct grid
{
	const int gridSize = GRID_DIV * GRID_DIV; // must be a power of 2
};

//---------------------------------------------CONFIGURE GUI---------------------------------------------//
class ofApp final : public ofBaseApp
{
public:
	void setup() override;
	void update() override;
	void draw() override;
	void keyPressed(int key) override;
	void restart();
	void random();
	void monads();
	void rndir();
	void rndprob();
	void rndvsc();
	void saveSettings();
	void loadSettings();
	void interaction(std::vector<point>* Group1, const std::vector<point>* Group2, float G, float radius, float viscosity, float probability);

	ofxPanel gui;

	ofxGuiGroup globalGroup;
	ofxGuiGroup rndGroup;
	ofxGuiGroup qtyGroup;
	ofxGuiGroup redGroup;
	ofxGuiGroup greenGroup;
	ofxGuiGroup blueGroup;
	ofxGuiGroup whiteGroup;
	ofxGuiGroup orangeGroup;
	ofxGuiGroup khakiGroup;
	ofxGuiGroup crimsonGroup;
	ofxGuiGroup darkGroup;
	ofxGuiGroup yellowGroup;
	ofxGuiGroup pinkGroup;
	ofxGuiGroup magentaGroup;
	ofxGuiGroup aquaGroup;
	ofxGuiGroup tealGroup;
	ofxGuiGroup silverGroup;
	ofxGuiGroup firebrickGroup;

	ofxButton resetButton;
	ofxButton selectButton;
	ofxButton save;
	ofxButton load;

	ofxButton randomGeneral;
	ofxButton randomCount;
	ofxButton randomChoice;
	ofxButton randomProb;
	ofxButton randomVsc;

	ofxToggle boundsToggle;
	ofxToggle modelToggle;
	ofxToggle motionBlurToggle;

	// some experimental stuff here
	ofxGuiGroup expGroup;
	ofxToggle evoToggle;
	ofxFloatSlider evoProbSlider;
	ofxFloatSlider evoAmountSlider;
	float evoChance = 0.1;
	float evoAmount = 0.5;
	ofxToggle radiusToogle;
	ofxLabel physicLabel;
	//end of experimental

	ofxFloatSlider viscositySlider;

	ofxFloatSlider viscositySliderRR;
	ofxFloatSlider viscositySliderRG;
	ofxFloatSlider viscositySliderRB;
	ofxFloatSlider viscositySliderRW;
	ofxFloatSlider viscositySliderRO;
	ofxFloatSlider viscositySliderRK;
	ofxFloatSlider viscositySliderRC;
	ofxFloatSlider viscositySliderRD;
	ofxFloatSlider viscositySliderRY;
	ofxFloatSlider viscositySliderRP;
	ofxFloatSlider viscositySliderRM;
	ofxFloatSlider viscositySliderRA;
	ofxFloatSlider viscositySliderRT;
	ofxFloatSlider viscositySliderRS;
	ofxFloatSlider viscositySliderRF;

	ofxFloatSlider viscositySliderGR;
	ofxFloatSlider viscositySliderGG;
	ofxFloatSlider viscositySliderGB;
	ofxFloatSlider viscositySliderGW;
	ofxFloatSlider viscositySliderGO;
	ofxFloatSlider viscositySliderGK;
	ofxFloatSlider viscositySliderGC;
	ofxFloatSlider viscositySliderGD;
	ofxFloatSlider viscositySliderGY;
	ofxFloatSlider viscositySliderGP;
	ofxFloatSlider viscositySliderGM;
	ofxFloatSlider viscositySliderGA;
	ofxFloatSlider viscositySliderGT;
	ofxFloatSlider viscositySliderGS;
	ofxFloatSlider viscositySliderGF;

	ofxFloatSlider viscositySliderBR;
	ofxFloatSlider viscositySliderBG;
	ofxFloatSlider viscositySliderBB;
	ofxFloatSlider viscositySliderBW;
	ofxFloatSlider viscositySliderBO;
	ofxFloatSlider viscositySliderBK;
	ofxFloatSlider viscositySliderBC;
	ofxFloatSlider viscositySliderBD;
	ofxFloatSlider viscositySliderBY;
	ofxFloatSlider viscositySliderBP;
	ofxFloatSlider viscositySliderBM;
	ofxFloatSlider viscositySliderBA;
	ofxFloatSlider viscositySliderBT;
	ofxFloatSlider viscositySliderBS;
	ofxFloatSlider viscositySliderBF;

	ofxFloatSlider viscositySliderWR;
	ofxFloatSlider viscositySliderWG;
	ofxFloatSlider viscositySliderWB;
	ofxFloatSlider viscositySliderWW;
	ofxFloatSlider viscositySliderWO;
	ofxFloatSlider viscositySliderWK;
	ofxFloatSlider viscositySliderWC;
	ofxFloatSlider viscositySliderWD;
	ofxFloatSlider viscositySliderWY;
	ofxFloatSlider viscositySliderWP;
	ofxFloatSlider viscositySliderWM;
	ofxFloatSlider viscositySliderWA;
	ofxFloatSlider viscositySliderWT;
	ofxFloatSlider viscositySliderWS;
	ofxFloatSlider viscositySliderWF;

	ofxFloatSlider viscositySliderOR;
	ofxFloatSlider viscositySliderOG;
	ofxFloatSlider viscositySliderOB;
	ofxFloatSlider viscositySliderOW;
	ofxFloatSlider viscositySliderOO;
	ofxFloatSlider viscositySliderOK;
	ofxFloatSlider viscositySliderOC;
	ofxFloatSlider viscositySliderOD;
	ofxFloatSlider viscositySliderOY;
	ofxFloatSlider viscositySliderOP;
	ofxFloatSlider viscositySliderOM;
	ofxFloatSlider viscositySliderOA;
	ofxFloatSlider viscositySliderOT;
	ofxFloatSlider viscositySliderOS;
	ofxFloatSlider viscositySliderOF;

	ofxFloatSlider viscositySliderKR;
	ofxFloatSlider viscositySliderKG;
	ofxFloatSlider viscositySliderKB;
	ofxFloatSlider viscositySliderKW;
	ofxFloatSlider viscositySliderKO;
	ofxFloatSlider viscositySliderKK;
	ofxFloatSlider viscositySliderKC;
	ofxFloatSlider viscositySliderKD;
	ofxFloatSlider viscositySliderKY;
	ofxFloatSlider viscositySliderKP;
	ofxFloatSlider viscositySliderKM;
	ofxFloatSlider viscositySliderKA;
	ofxFloatSlider viscositySliderKT;
	ofxFloatSlider viscositySliderKS;
	ofxFloatSlider viscositySliderKF;

	ofxFloatSlider viscositySliderCR;
	ofxFloatSlider viscositySliderCG;
	ofxFloatSlider viscositySliderCB;
	ofxFloatSlider viscositySliderCW;
	ofxFloatSlider viscositySliderCO;
	ofxFloatSlider viscositySliderCK;
	ofxFloatSlider viscositySliderCC;
	ofxFloatSlider viscositySliderCD;
	ofxFloatSlider viscositySliderCY;
	ofxFloatSlider viscositySliderCP;
	ofxFloatSlider viscositySliderCM;
	ofxFloatSlider viscositySliderCA;
	ofxFloatSlider viscositySliderCT;
	ofxFloatSlider viscositySliderCS;
	ofxFloatSlider viscositySliderCF;

	ofxFloatSlider viscositySliderDR;
	ofxFloatSlider viscositySliderDG;
	ofxFloatSlider viscositySliderDB;
	ofxFloatSlider viscositySliderDW;
	ofxFloatSlider viscositySliderDO;
	ofxFloatSlider viscositySliderDK;
	ofxFloatSlider viscositySliderDC;
	ofxFloatSlider viscositySliderDD;
	ofxFloatSlider viscositySliderDY;
	ofxFloatSlider viscositySliderDP;
	ofxFloatSlider viscositySliderDM;
	ofxFloatSlider viscositySliderDA;
	ofxFloatSlider viscositySliderDT;
	ofxFloatSlider viscositySliderDS;
	ofxFloatSlider viscositySliderDF;

	ofxFloatSlider viscositySliderYR;
	ofxFloatSlider viscositySliderYG;
	ofxFloatSlider viscositySliderYB;
	ofxFloatSlider viscositySliderYW;
	ofxFloatSlider viscositySliderYO;
	ofxFloatSlider viscositySliderYK;
	ofxFloatSlider viscositySliderYC;
	ofxFloatSlider viscositySliderYD;
	ofxFloatSlider viscositySliderYY;
	ofxFloatSlider viscositySliderYP;
	ofxFloatSlider viscositySliderYM;
	ofxFloatSlider viscositySliderYA;
	ofxFloatSlider viscositySliderYT;
	ofxFloatSlider viscositySliderYS;
	ofxFloatSlider viscositySliderYF;

	ofxFloatSlider viscositySliderPR;
	ofxFloatSlider viscositySliderPG;
	ofxFloatSlider viscositySliderPB;
	ofxFloatSlider viscositySliderPW;
	ofxFloatSlider viscositySliderPO;
	ofxFloatSlider viscositySliderPK;
	ofxFloatSlider viscositySliderPC;
	ofxFloatSlider viscositySliderPD;
	ofxFloatSlider viscositySliderPY;
	ofxFloatSlider viscositySliderPP;
	ofxFloatSlider viscositySliderPM;
	ofxFloatSlider viscositySliderPA;
	ofxFloatSlider viscositySliderPT;
	ofxFloatSlider viscositySliderPS;
	ofxFloatSlider viscositySliderPF;

	ofxFloatSlider viscositySliderMR;
	ofxFloatSlider viscositySliderMG;
	ofxFloatSlider viscositySliderMB;
	ofxFloatSlider viscositySliderMW;
	ofxFloatSlider viscositySliderMO;
	ofxFloatSlider viscositySliderMK;
	ofxFloatSlider viscositySliderMC;
	ofxFloatSlider viscositySliderMD;
	ofxFloatSlider viscositySliderMY;
	ofxFloatSlider viscositySliderMP;
	ofxFloatSlider viscositySliderMM;
	ofxFloatSlider viscositySliderMA;
	ofxFloatSlider viscositySliderMT;
	ofxFloatSlider viscositySliderMS;
	ofxFloatSlider viscositySliderMF;

	ofxFloatSlider viscositySliderAR;
	ofxFloatSlider viscositySliderAG;
	ofxFloatSlider viscositySliderAB;
	ofxFloatSlider viscositySliderAW;
	ofxFloatSlider viscositySliderAO;
	ofxFloatSlider viscositySliderAK;
	ofxFloatSlider viscositySliderAC;
	ofxFloatSlider viscositySliderAD;
	ofxFloatSlider viscositySliderAY;
	ofxFloatSlider viscositySliderAP;
	ofxFloatSlider viscositySliderAM;
	ofxFloatSlider viscositySliderAA;
	ofxFloatSlider viscositySliderAT;
	ofxFloatSlider viscositySliderAS;
	ofxFloatSlider viscositySliderAF;

	ofxFloatSlider viscositySliderTR;
	ofxFloatSlider viscositySliderTG;
	ofxFloatSlider viscositySliderTB;
	ofxFloatSlider viscositySliderTW;
	ofxFloatSlider viscositySliderTO;
	ofxFloatSlider viscositySliderTK;
	ofxFloatSlider viscositySliderTC;
	ofxFloatSlider viscositySliderTD;
	ofxFloatSlider viscositySliderTY;
	ofxFloatSlider viscositySliderTP;
	ofxFloatSlider viscositySliderTM;
	ofxFloatSlider viscositySliderTA;
	ofxFloatSlider viscositySliderTT;
	ofxFloatSlider viscositySliderTS;
	ofxFloatSlider viscositySliderTF;

	ofxFloatSlider viscositySliderSR;
	ofxFloatSlider viscositySliderSG;
	ofxFloatSlider viscositySliderSB;
	ofxFloatSlider viscositySliderSW;
	ofxFloatSlider viscositySliderSO;
	ofxFloatSlider viscositySliderSK;
	ofxFloatSlider viscositySliderSC;
	ofxFloatSlider viscositySliderSD;
	ofxFloatSlider viscositySliderSY;
	ofxFloatSlider viscositySliderSP;
	ofxFloatSlider viscositySliderSM;
	ofxFloatSlider viscositySliderSA;
	ofxFloatSlider viscositySliderST;
	ofxFloatSlider viscositySliderSS;
	ofxFloatSlider viscositySliderSF;

	ofxFloatSlider viscositySliderFR;
	ofxFloatSlider viscositySliderFG;
	ofxFloatSlider viscositySliderFB;
	ofxFloatSlider viscositySliderFW;
	ofxFloatSlider viscositySliderFO;
	ofxFloatSlider viscositySliderFK;
	ofxFloatSlider viscositySliderFC;
	ofxFloatSlider viscositySliderFD;
	ofxFloatSlider viscositySliderFY;
	ofxFloatSlider viscositySliderFP;
	ofxFloatSlider viscositySliderFM;
	ofxFloatSlider viscositySliderFA;
	ofxFloatSlider viscositySliderFT;
	ofxFloatSlider viscositySliderFS;
	ofxFloatSlider viscositySliderFF;

	ofxFloatSlider probabilitySlider;

	ofxFloatSlider probabilitySliderRR;
	ofxFloatSlider probabilitySliderRG;
	ofxFloatSlider probabilitySliderRB;
	ofxFloatSlider probabilitySliderRW;
	ofxFloatSlider probabilitySliderRO;
	ofxFloatSlider probabilitySliderRK;
	ofxFloatSlider probabilitySliderRC;
	ofxFloatSlider probabilitySliderRD;
	ofxFloatSlider probabilitySliderRY;
	ofxFloatSlider probabilitySliderRP;
	ofxFloatSlider probabilitySliderRM;
	ofxFloatSlider probabilitySliderRA;
	ofxFloatSlider probabilitySliderRT;
	ofxFloatSlider probabilitySliderRS;
	ofxFloatSlider probabilitySliderRF;

	ofxFloatSlider probabilitySliderGR;
	ofxFloatSlider probabilitySliderGG;
	ofxFloatSlider probabilitySliderGB;
	ofxFloatSlider probabilitySliderGW;
	ofxFloatSlider probabilitySliderGO;
	ofxFloatSlider probabilitySliderGK;
	ofxFloatSlider probabilitySliderGC;
	ofxFloatSlider probabilitySliderGD;
	ofxFloatSlider probabilitySliderGY;
	ofxFloatSlider probabilitySliderGP;
	ofxFloatSlider probabilitySliderGM;
	ofxFloatSlider probabilitySliderGA;
	ofxFloatSlider probabilitySliderGT;
	ofxFloatSlider probabilitySliderGS;
	ofxFloatSlider probabilitySliderGF;

	ofxFloatSlider probabilitySliderBR;
	ofxFloatSlider probabilitySliderBG;
	ofxFloatSlider probabilitySliderBB;
	ofxFloatSlider probabilitySliderBW;
	ofxFloatSlider probabilitySliderBO;
	ofxFloatSlider probabilitySliderBK;
	ofxFloatSlider probabilitySliderBC;
	ofxFloatSlider probabilitySliderBD;
	ofxFloatSlider probabilitySliderBY;
	ofxFloatSlider probabilitySliderBP;
	ofxFloatSlider probabilitySliderBM;
	ofxFloatSlider probabilitySliderBA;
	ofxFloatSlider probabilitySliderBT;
	ofxFloatSlider probabilitySliderBS;
	ofxFloatSlider probabilitySliderBF;

	ofxFloatSlider probabilitySliderWR;
	ofxFloatSlider probabilitySliderWG;
	ofxFloatSlider probabilitySliderWB;
	ofxFloatSlider probabilitySliderWW;
	ofxFloatSlider probabilitySliderWO;
	ofxFloatSlider probabilitySliderWK;
	ofxFloatSlider probabilitySliderWC;
	ofxFloatSlider probabilitySliderWD;
	ofxFloatSlider probabilitySliderWY;
	ofxFloatSlider probabilitySliderWP;
	ofxFloatSlider probabilitySliderWM;
	ofxFloatSlider probabilitySliderWA;
	ofxFloatSlider probabilitySliderWT;
	ofxFloatSlider probabilitySliderWS;
	ofxFloatSlider probabilitySliderWF;

	ofxFloatSlider probabilitySliderOR;
	ofxFloatSlider probabilitySliderOG;
	ofxFloatSlider probabilitySliderOB;
	ofxFloatSlider probabilitySliderOW;
	ofxFloatSlider probabilitySliderOO;
	ofxFloatSlider probabilitySliderOK;
	ofxFloatSlider probabilitySliderOC;
	ofxFloatSlider probabilitySliderOD;
	ofxFloatSlider probabilitySliderOY;
	ofxFloatSlider probabilitySliderOP;
	ofxFloatSlider probabilitySliderOM;
	ofxFloatSlider probabilitySliderOA;
	ofxFloatSlider probabilitySliderOT;
	ofxFloatSlider probabilitySliderOS;
	ofxFloatSlider probabilitySliderOF;

	ofxFloatSlider probabilitySliderKR;
	ofxFloatSlider probabilitySliderKG;
	ofxFloatSlider probabilitySliderKB;
	ofxFloatSlider probabilitySliderKW;
	ofxFloatSlider probabilitySliderKO;
	ofxFloatSlider probabilitySliderKK;
	ofxFloatSlider probabilitySliderKC;
	ofxFloatSlider probabilitySliderKD;
	ofxFloatSlider probabilitySliderKY;
	ofxFloatSlider probabilitySliderKP;
	ofxFloatSlider probabilitySliderKM;
	ofxFloatSlider probabilitySliderKA;
	ofxFloatSlider probabilitySliderKT;
	ofxFloatSlider probabilitySliderKS;
	ofxFloatSlider probabilitySliderKF;

	ofxFloatSlider probabilitySliderCR;
	ofxFloatSlider probabilitySliderCG;
	ofxFloatSlider probabilitySliderCB;
	ofxFloatSlider probabilitySliderCW;
	ofxFloatSlider probabilitySliderCO;
	ofxFloatSlider probabilitySliderCK;
	ofxFloatSlider probabilitySliderCC;
	ofxFloatSlider probabilitySliderCD;
	ofxFloatSlider probabilitySliderCY;
	ofxFloatSlider probabilitySliderCP;
	ofxFloatSlider probabilitySliderCM;
	ofxFloatSlider probabilitySliderCA;
	ofxFloatSlider probabilitySliderCT;
	ofxFloatSlider probabilitySliderCS;
	ofxFloatSlider probabilitySliderCF;

	ofxFloatSlider probabilitySliderDR;
	ofxFloatSlider probabilitySliderDG;
	ofxFloatSlider probabilitySliderDB;
	ofxFloatSlider probabilitySliderDW;
	ofxFloatSlider probabilitySliderDO;
	ofxFloatSlider probabilitySliderDK;
	ofxFloatSlider probabilitySliderDC;
	ofxFloatSlider probabilitySliderDD;
	ofxFloatSlider probabilitySliderDY;
	ofxFloatSlider probabilitySliderDP;
	ofxFloatSlider probabilitySliderDM;
	ofxFloatSlider probabilitySliderDA;
	ofxFloatSlider probabilitySliderDT;
	ofxFloatSlider probabilitySliderDS;
	ofxFloatSlider probabilitySliderDF;

	ofxFloatSlider probabilitySliderYR;
	ofxFloatSlider probabilitySliderYG;
	ofxFloatSlider probabilitySliderYB;
	ofxFloatSlider probabilitySliderYW;
	ofxFloatSlider probabilitySliderYO;
	ofxFloatSlider probabilitySliderYK;
	ofxFloatSlider probabilitySliderYC;
	ofxFloatSlider probabilitySliderYD;
	ofxFloatSlider probabilitySliderYY;
	ofxFloatSlider probabilitySliderYP;
	ofxFloatSlider probabilitySliderYM;
	ofxFloatSlider probabilitySliderYA;
	ofxFloatSlider probabilitySliderYT;
	ofxFloatSlider probabilitySliderYS;
	ofxFloatSlider probabilitySliderYF;

	ofxFloatSlider probabilitySliderPR;
	ofxFloatSlider probabilitySliderPG;
	ofxFloatSlider probabilitySliderPB;
	ofxFloatSlider probabilitySliderPW;
	ofxFloatSlider probabilitySliderPO;
	ofxFloatSlider probabilitySliderPK;
	ofxFloatSlider probabilitySliderPC;
	ofxFloatSlider probabilitySliderPD;
	ofxFloatSlider probabilitySliderPY;
	ofxFloatSlider probabilitySliderPP;
	ofxFloatSlider probabilitySliderPM;
	ofxFloatSlider probabilitySliderPA;
	ofxFloatSlider probabilitySliderPT;
	ofxFloatSlider probabilitySliderPS;
	ofxFloatSlider probabilitySliderPF;

	ofxFloatSlider probabilitySliderMR;
	ofxFloatSlider probabilitySliderMG;
	ofxFloatSlider probabilitySliderMB;
	ofxFloatSlider probabilitySliderMW;
	ofxFloatSlider probabilitySliderMO;
	ofxFloatSlider probabilitySliderMK;
	ofxFloatSlider probabilitySliderMC;
	ofxFloatSlider probabilitySliderMD;
	ofxFloatSlider probabilitySliderMY;
	ofxFloatSlider probabilitySliderMP;
	ofxFloatSlider probabilitySliderMM;
	ofxFloatSlider probabilitySliderMA;
	ofxFloatSlider probabilitySliderMT;
	ofxFloatSlider probabilitySliderMS;
	ofxFloatSlider probabilitySliderMF;

	ofxFloatSlider probabilitySliderAR;
	ofxFloatSlider probabilitySliderAG;
	ofxFloatSlider probabilitySliderAB;
	ofxFloatSlider probabilitySliderAW;
	ofxFloatSlider probabilitySliderAO;
	ofxFloatSlider probabilitySliderAK;
	ofxFloatSlider probabilitySliderAC;
	ofxFloatSlider probabilitySliderAD;
	ofxFloatSlider probabilitySliderAY;
	ofxFloatSlider probabilitySliderAP;
	ofxFloatSlider probabilitySliderAM;
	ofxFloatSlider probabilitySliderAA;
	ofxFloatSlider probabilitySliderAT;
	ofxFloatSlider probabilitySliderAS;
	ofxFloatSlider probabilitySliderAF;

	ofxFloatSlider probabilitySliderTR;
	ofxFloatSlider probabilitySliderTG;
	ofxFloatSlider probabilitySliderTB;
	ofxFloatSlider probabilitySliderTW;
	ofxFloatSlider probabilitySliderTO;
	ofxFloatSlider probabilitySliderTK;
	ofxFloatSlider probabilitySliderTC;
	ofxFloatSlider probabilitySliderTD;
	ofxFloatSlider probabilitySliderTY;
	ofxFloatSlider probabilitySliderTP;
	ofxFloatSlider probabilitySliderTM;
	ofxFloatSlider probabilitySliderTA;
	ofxFloatSlider probabilitySliderTT;
	ofxFloatSlider probabilitySliderTS;
	ofxFloatSlider probabilitySliderTF;

	ofxFloatSlider probabilitySliderSR;
	ofxFloatSlider probabilitySliderSG;
	ofxFloatSlider probabilitySliderSB;
	ofxFloatSlider probabilitySliderSW;
	ofxFloatSlider probabilitySliderSO;
	ofxFloatSlider probabilitySliderSK;
	ofxFloatSlider probabilitySliderSC;
	ofxFloatSlider probabilitySliderSD;
	ofxFloatSlider probabilitySliderSY;
	ofxFloatSlider probabilitySliderSP;
	ofxFloatSlider probabilitySliderSM;
	ofxFloatSlider probabilitySliderSA;
	ofxFloatSlider probabilitySliderST;
	ofxFloatSlider probabilitySliderSS;
	ofxFloatSlider probabilitySliderSF;

	ofxFloatSlider probabilitySliderFR;
	ofxFloatSlider probabilitySliderFG;
	ofxFloatSlider probabilitySliderFB;
	ofxFloatSlider probabilitySliderFW;
	ofxFloatSlider probabilitySliderFO;
	ofxFloatSlider probabilitySliderFK;
	ofxFloatSlider probabilitySliderFC;
	ofxFloatSlider probabilitySliderFD;
	ofxFloatSlider probabilitySliderFY;
	ofxFloatSlider probabilitySliderFP;
	ofxFloatSlider probabilitySliderFM;
	ofxFloatSlider probabilitySliderFA;
	ofxFloatSlider probabilitySliderFT;
	ofxFloatSlider probabilitySliderFS;
	ofxFloatSlider probabilitySliderFF;

	unsigned int probability = 90.00;

	unsigned int probabilityRR = 10.00;
	unsigned int probabilityRG = 15.00;
	unsigned int probabilityRB = 20.00;
	unsigned int probabilityRW = 25.00;
	unsigned int probabilityRO = 30.00;
	unsigned int probabilityRK = 35.00;
	unsigned int probabilityRC = 40.00;
	unsigned int probabilityRD = 45.00;
	unsigned int probabilityRY = 50.00;
	unsigned int probabilityRP = 55.00;
	unsigned int probabilityRM = 60.00;
	unsigned int probabilityRA = 65.00;
	unsigned int probabilityRT = 70.00;
	unsigned int probabilityRS = 75.00;
	unsigned int probabilityRF = 80.00;

	unsigned int probabilityGR = 90.00;
	unsigned int probabilityGG = 95.00;
	unsigned int probabilityGB = 100.00;
	unsigned int probabilityGW = 0.00;
	unsigned int probabilityGO = 5.00;
	unsigned int probabilityGK = 10.00;
	unsigned int probabilityGC = 15.00;
	unsigned int probabilityGD = 20.00;
	unsigned int probabilityGY = 25.00;
	unsigned int probabilityGP = 30.00;
	unsigned int probabilityGM = 35.00;
	unsigned int probabilityGA = 40.00;
	unsigned int probabilityGT = 45.00;
	unsigned int probabilityGS = 50.00;
	unsigned int probabilityGF = 55.00;

	unsigned int probabilityBR = 60.00;
	unsigned int probabilityBG = 65.00;
	unsigned int probabilityBB = 70.00;
	unsigned int probabilityBW = 75.00;
	unsigned int probabilityBO = 80.00;
	unsigned int probabilityBK = 85.00;
	unsigned int probabilityBC = 90.00;
	unsigned int probabilityBD = 95.00;
	unsigned int probabilityBY = 100.00;
	unsigned int probabilityBP = 0.00;
	unsigned int probabilityBM = 3.00;
	unsigned int probabilityBA = 6.00;
	unsigned int probabilityBT = 9.00;
	unsigned int probabilityBS = 12.00;
	unsigned int probabilityBF = 15.00;

	unsigned int probabilityWR = 18.00;
	unsigned int probabilityWG = 21.00;
	unsigned int probabilityWB = 24.00;
	unsigned int probabilityWW = 27.00;
	unsigned int probabilityWO = 30.00;
	unsigned int probabilityWK = 33.00;
	unsigned int probabilityWC = 36.00;
	unsigned int probabilityWD = 39.00;
	unsigned int probabilityWY = 42.00;
	unsigned int probabilityWP = 45.00;
	unsigned int probabilityWM = 48.00;
	unsigned int probabilityWA = 51.00;
	unsigned int probabilityWT = 54.00;
	unsigned int probabilityWS = 57.00;
	unsigned int probabilityWF = 60.00;

	unsigned int probabilityOR = 63.00;
	unsigned int probabilityOG = 66.00;
	unsigned int probabilityOB = 69.00;
	unsigned int probabilityOW = 72.00;
	unsigned int probabilityOO = 75.00;
	unsigned int probabilityOK = 78.00;
	unsigned int probabilityOC = 81.00;
	unsigned int probabilityOD = 84.00;
	unsigned int probabilityOY = 87.00;
	unsigned int probabilityOP = 90.00;
	unsigned int probabilityOM = 93.00;
	unsigned int probabilityOA = 96.00;
	unsigned int probabilityOT = 99.00;
	unsigned int probabilityOS = 2.00;
	unsigned int probabilityOF = 4.00;

	unsigned int probabilityKR = 6.00;
	unsigned int probabilityKG = 8.00;
	unsigned int probabilityKB = 10.00;
	unsigned int probabilityKW = 12.00;
	unsigned int probabilityKO = 14.00;
	unsigned int probabilityKK = 16.00;
	unsigned int probabilityKC = 18.00;
	unsigned int probabilityKD = 20.00;
	unsigned int probabilityKY = 22.00;
	unsigned int probabilityKP = 24.00;
	unsigned int probabilityKM = 26.00;
	unsigned int probabilityKA = 28.00;
	unsigned int probabilityKT = 30.00;
	unsigned int probabilityKS = 32.00;
	unsigned int probabilityKF = 34.00;

	unsigned int probabilityCR = 36.00;
	unsigned int probabilityCG = 38.00;
	unsigned int probabilityCB = 40.00;
	unsigned int probabilityCW = 42.00;
	unsigned int probabilityCO = 44.00;
	unsigned int probabilityCK = 46.00;
	unsigned int probabilityCC = 48.00;
	unsigned int probabilityCD = 50.00;
	unsigned int probabilityCY = 52.00;
	unsigned int probabilityCP = 54.00;
	unsigned int probabilityCM = 56.00;
	unsigned int probabilityCA = 58.00;
	unsigned int probabilityCT = 60.00;
	unsigned int probabilityCS = 62.00;
	unsigned int probabilityCF = 64.00;

	unsigned int probabilityDR = 66.00;
	unsigned int probabilityDG = 68.00;
	unsigned int probabilityDB = 70.00;
	unsigned int probabilityDW = 72.00;
	unsigned int probabilityDO = 74.00;
	unsigned int probabilityDK = 76.00;
	unsigned int probabilityDC = 78.00;
	unsigned int probabilityDD = 80.00;
	unsigned int probabilityDY = 82.00;
	unsigned int probabilityDP = 84.00;
	unsigned int probabilityDM = 86.00;
	unsigned int probabilityDA = 88.00;
	unsigned int probabilityDT = 90.00;
	unsigned int probabilityDS = 92.00;
	unsigned int probabilityDF = 94.00;

	unsigned int probabilityYR = 96.00;
	unsigned int probabilityYG = 98.00;
	unsigned int probabilityYB = 70.00;
	unsigned int probabilityYW = 72.00;
	unsigned int probabilityYO = 74.00;
	unsigned int probabilityYK = 76.00;
	unsigned int probabilityYC = 78.00;
	unsigned int probabilityYD = 80.00;
	unsigned int probabilityYY = 82.00;
	unsigned int probabilityYP = 84.00;
	unsigned int probabilityYM = 86.00;
	unsigned int probabilityYA = 88.00;
	unsigned int probabilityYT = 90.00;
	unsigned int probabilityYS = 92.00;
	unsigned int probabilityYF = 94.00;

	unsigned int probabilityPR = 66.00;
	unsigned int probabilityPG = 68.00;
	unsigned int probabilityPB = 70.00;
	unsigned int probabilityPW = 72.00;
	unsigned int probabilityPO = 74.00;
	unsigned int probabilityPK = 76.00;
	unsigned int probabilityPC = 78.00;
	unsigned int probabilityPD = 80.00;
	unsigned int probabilityPY = 82.00;
	unsigned int probabilityPP = 84.00;
	unsigned int probabilityPM = 86.00;
	unsigned int probabilityPA = 88.00;
	unsigned int probabilityPT = 90.00;
	unsigned int probabilityPS = 92.00;
	unsigned int probabilityPF = 94.00;

	unsigned int probabilityMR = 66.00;
	unsigned int probabilityMG = 68.00;
	unsigned int probabilityMB = 70.00;
	unsigned int probabilityMW = 72.00;
	unsigned int probabilityMO = 74.00;
	unsigned int probabilityMK = 76.00;
	unsigned int probabilityMC = 78.00;
	unsigned int probabilityMD = 80.00;
	unsigned int probabilityMY = 82.00;
	unsigned int probabilityMP = 84.00;
	unsigned int probabilityMM = 86.00;
	unsigned int probabilityMA = 88.00;
	unsigned int probabilityMT = 90.00;
	unsigned int probabilityMS = 92.00;
	unsigned int probabilityMF = 94.00;

	unsigned int probabilityAR = 66.00;
	unsigned int probabilityAG = 68.00;
	unsigned int probabilityAB = 70.00;
	unsigned int probabilityAW = 72.00;
	unsigned int probabilityAO = 74.00;
	unsigned int probabilityAK = 76.00;
	unsigned int probabilityAC = 78.00;
	unsigned int probabilityAD = 80.00;
	unsigned int probabilityAY = 82.00;
	unsigned int probabilityAP = 84.00;
	unsigned int probabilityAM = 86.00;
	unsigned int probabilityAA = 88.00;
	unsigned int probabilityAT = 90.00;
	unsigned int probabilityAS = 92.00;
	unsigned int probabilityAF = 94.00;

	unsigned int probabilityTR = 66.00;
	unsigned int probabilityTG = 68.00;
	unsigned int probabilityTB = 70.00;
	unsigned int probabilityTW = 72.00;
	unsigned int probabilityTO = 74.00;
	unsigned int probabilityTK = 76.00;
	unsigned int probabilityTC = 78.00;
	unsigned int probabilityTD = 80.00;
	unsigned int probabilityTY = 82.00;
	unsigned int probabilityTP = 84.00;
	unsigned int probabilityTM = 86.00;
	unsigned int probabilityTA = 88.00;
	unsigned int probabilityTT = 90.00;
	unsigned int probabilityTS = 92.00;
	unsigned int probabilityTF = 94.00;

	unsigned int probabilitySR = 66.00;
	unsigned int probabilitySG = 68.00;
	unsigned int probabilitySB = 70.00;
	unsigned int probabilitySW = 72.00;
	unsigned int probabilitySO = 74.00;
	unsigned int probabilitySK = 76.00;
	unsigned int probabilitySC = 78.00;
	unsigned int probabilitySD = 80.00;
	unsigned int probabilitySY = 82.00;
	unsigned int probabilitySP = 84.00;
	unsigned int probabilitySM = 86.00;
	unsigned int probabilitySA = 88.00;
	unsigned int probabilityST = 90.00;
	unsigned int probabilitySS = 92.00;
	unsigned int probabilitySF = 94.00;

	unsigned int probabilityFR = 66.00;
	unsigned int probabilityFG = 68.00;
	unsigned int probabilityFB = 70.00;
	unsigned int probabilityFW = 72.00;
	unsigned int probabilityFO = 74.00;
	unsigned int probabilityFK = 76.00;
	unsigned int probabilityFC = 78.00;
	unsigned int probabilityFD = 80.00;
	unsigned int probabilityFY = 82.00;
	unsigned int probabilityFP = 84.00;
	unsigned int probabilityFM = 86.00;
	unsigned int probabilityFA = 88.00;
	unsigned int probabilityFT = 90.00;
	unsigned int probabilityFS = 92.00;
	unsigned int probabilityFF = 94.00;

	ofxIntSlider numberSliderR;
	ofxIntSlider numberSliderG;
	ofxIntSlider numberSliderW;
	ofxIntSlider numberSliderB;
	ofxIntSlider numberSliderO;
	ofxIntSlider numberSliderK;
	ofxIntSlider numberSliderC;
	ofxIntSlider numberSliderD;
	ofxIntSlider numberSliderY;
	ofxIntSlider numberSliderP;
	ofxIntSlider numberSliderM;
	ofxIntSlider numberSliderA;
	ofxIntSlider numberSliderT;
	ofxIntSlider numberSliderS;
	ofxIntSlider numberSliderF;

	int pnumberSliderR = 1000;
	int pnumberSliderG = 1000;
	int pnumberSliderW = 1000;
	int pnumberSliderB = 1000;
	int pnumberSliderO = 1000;
	int pnumberSliderK = 1000;
	int pnumberSliderC = 1000;
	int pnumberSliderD = 1000;
	int pnumberSliderY = 1000;
	int pnumberSliderP = 1000;
	int pnumberSliderM = 1000;
	int pnumberSliderA = 1000;
	int pnumberSliderT = 1000;
	int pnumberSliderS = 1000;
	int pnumberSliderF = 1000;

	ofxFloatSlider gravitySlider;
	ofxFloatSlider wallRepelSlider;

	ofxFloatSlider powerSliderRR;
	ofxFloatSlider powerSliderRG;
	ofxFloatSlider powerSliderRW;
	ofxFloatSlider powerSliderRB;
	ofxFloatSlider powerSliderRO;
	ofxFloatSlider powerSliderRK;
	ofxFloatSlider powerSliderRC;
	ofxFloatSlider powerSliderRD;
	ofxFloatSlider powerSliderRY;
	ofxFloatSlider powerSliderRP;
	ofxFloatSlider powerSliderRM;
	ofxFloatSlider powerSliderRA;
	ofxFloatSlider powerSliderRT;
	ofxFloatSlider powerSliderRS;
	ofxFloatSlider powerSliderRF;

	float ppowerSliderRR = 0;
	float ppowerSliderRG = 0;
	float ppowerSliderRW = 0;
	float ppowerSliderRB = 0;
	float ppowerSliderRO = 0;
	float ppowerSliderRK = 0;
	float ppowerSliderRC = 0;
	float ppowerSliderRD = 0;
	float ppowerSliderRY = 0;
	float ppowerSliderRP = 0;
	float ppowerSliderRM = 0;
	float ppowerSliderRA = 0;
	float ppowerSliderRT = 0;
	float ppowerSliderRS = 0;
	float ppowerSliderRF = 0;

	ofxFloatSlider powerSliderGR;
	ofxFloatSlider powerSliderGG;
	ofxFloatSlider powerSliderGW;
	ofxFloatSlider powerSliderGB;
	ofxFloatSlider powerSliderGO;
	ofxFloatSlider powerSliderGK;
	ofxFloatSlider powerSliderGC;
	ofxFloatSlider powerSliderGD;
	ofxFloatSlider powerSliderGY;
	ofxFloatSlider powerSliderGP;
	ofxFloatSlider powerSliderGM;
	ofxFloatSlider powerSliderGA;
	ofxFloatSlider powerSliderGT;
	ofxFloatSlider powerSliderGS;
	ofxFloatSlider powerSliderGF;

	float ppowerSliderGR = 0;
	float ppowerSliderGG = 0;
	float ppowerSliderGW = 0;
	float ppowerSliderGB = 0;
	float ppowerSliderGO = 0;
	float ppowerSliderGK = 0;
	float ppowerSliderGC = 0;
	float ppowerSliderGD = 0;
	float ppowerSliderGY = 0;
	float ppowerSliderGP = 0;
	float ppowerSliderGM = 0;
	float ppowerSliderGA = 0;
	float ppowerSliderGT = 0;
	float ppowerSliderGS = 0;
	float ppowerSliderGF = 0;

	ofxFloatSlider powerSliderWR;
	ofxFloatSlider powerSliderWG;
	ofxFloatSlider powerSliderWW;
	ofxFloatSlider powerSliderWB;
	ofxFloatSlider powerSliderWO;
	ofxFloatSlider powerSliderWK;
	ofxFloatSlider powerSliderWC;
	ofxFloatSlider powerSliderWD;
	ofxFloatSlider powerSliderWY;
	ofxFloatSlider powerSliderWP;
	ofxFloatSlider powerSliderWM;
	ofxFloatSlider powerSliderWA;
	ofxFloatSlider powerSliderWT;
	ofxFloatSlider powerSliderWS;
	ofxFloatSlider powerSliderWF;

	float ppowerSliderWR = 0;
	float ppowerSliderWG = 0;
	float ppowerSliderWW = 0;
	float ppowerSliderWB = 0;
	float ppowerSliderWO = 0;
	float ppowerSliderWK = 0;
	float ppowerSliderWC = 0;
	float ppowerSliderWD = 0;
	float ppowerSliderWY = 0;
	float ppowerSliderWP = 0;
	float ppowerSliderWM = 0;
	float ppowerSliderWA = 0;
	float ppowerSliderWT = 0;
	float ppowerSliderWS = 0;
	float ppowerSliderWF = 0;

	ofxFloatSlider powerSliderBR;
	ofxFloatSlider powerSliderBG;
	ofxFloatSlider powerSliderBW;
	ofxFloatSlider powerSliderBB;
	ofxFloatSlider powerSliderBO;
	ofxFloatSlider powerSliderBK;
	ofxFloatSlider powerSliderBC;
	ofxFloatSlider powerSliderBD;
	ofxFloatSlider powerSliderBY;
	ofxFloatSlider powerSliderBP;
	ofxFloatSlider powerSliderBM;
	ofxFloatSlider powerSliderBA;
	ofxFloatSlider powerSliderBT;
	ofxFloatSlider powerSliderBS;
	ofxFloatSlider powerSliderBF;

	float ppowerSliderBR = 0;
	float ppowerSliderBG = 0;
	float ppowerSliderBW = 0;
	float ppowerSliderBB = 0;
	float ppowerSliderBO = 0;
	float ppowerSliderBK = 0;
	float ppowerSliderBC = 0;
	float ppowerSliderBD = 0;
	float ppowerSliderBY = 0;
	float ppowerSliderBP = 0;
	float ppowerSliderBM = 0;
	float ppowerSliderBA = 0;
	float ppowerSliderBT = 0;
	float ppowerSliderBS = 0;
	float ppowerSliderBF = 0;

	ofxFloatSlider powerSliderOR;
	ofxFloatSlider powerSliderOG;
	ofxFloatSlider powerSliderOW;
	ofxFloatSlider powerSliderOB;
	ofxFloatSlider powerSliderOO;
	ofxFloatSlider powerSliderOK;
	ofxFloatSlider powerSliderOC;
	ofxFloatSlider powerSliderOD;
	ofxFloatSlider powerSliderOY;
	ofxFloatSlider powerSliderOP;
	ofxFloatSlider powerSliderOM;
	ofxFloatSlider powerSliderOA;
	ofxFloatSlider powerSliderOT;
	ofxFloatSlider powerSliderOS;
	ofxFloatSlider powerSliderOF;

	float ppowerSliderOR = 0;
	float ppowerSliderOG = 0;
	float ppowerSliderOW = 0;
	float ppowerSliderOB = 0;
	float ppowerSliderOO = 0;
	float ppowerSliderOK = 0;
	float ppowerSliderOC = 0;
	float ppowerSliderOD = 0;
	float ppowerSliderOY = 0;
	float ppowerSliderOP = 0;
	float ppowerSliderOM = 0;
	float ppowerSliderOA = 0;
	float ppowerSliderOT = 0;
	float ppowerSliderOS = 0;
	float ppowerSliderOF = 0;

	ofxFloatSlider powerSliderKR;
	ofxFloatSlider powerSliderKG;
	ofxFloatSlider powerSliderKW;
	ofxFloatSlider powerSliderKB;
	ofxFloatSlider powerSliderKO;
	ofxFloatSlider powerSliderKK;
	ofxFloatSlider powerSliderKC;
	ofxFloatSlider powerSliderKD;
	ofxFloatSlider powerSliderKY;
	ofxFloatSlider powerSliderKP;
	ofxFloatSlider powerSliderKM;
	ofxFloatSlider powerSliderKA;
	ofxFloatSlider powerSliderKT;
	ofxFloatSlider powerSliderKS;
	ofxFloatSlider powerSliderKF;

	float ppowerSliderKR = 0;
	float ppowerSliderKG = 0;
	float ppowerSliderKW = 0;
	float ppowerSliderKB = 0;
	float ppowerSliderKO = 0;
	float ppowerSliderKK = 0;
	float ppowerSliderKC = 0;
	float ppowerSliderKD = 0;
	float ppowerSliderKY = 0;
	float ppowerSliderKP = 0;
	float ppowerSliderKM = 0;
	float ppowerSliderKA = 0;
	float ppowerSliderKT = 0;
	float ppowerSliderKS = 0;
	float ppowerSliderKF = 0;

	ofxFloatSlider powerSliderCR;
	ofxFloatSlider powerSliderCG;
	ofxFloatSlider powerSliderCW;
	ofxFloatSlider powerSliderCB;
	ofxFloatSlider powerSliderCO;
	ofxFloatSlider powerSliderCK;
	ofxFloatSlider powerSliderCC;
	ofxFloatSlider powerSliderCD;
	ofxFloatSlider powerSliderCY;
	ofxFloatSlider powerSliderCP;
	ofxFloatSlider powerSliderCM;
	ofxFloatSlider powerSliderCA;
	ofxFloatSlider powerSliderCT;
	ofxFloatSlider powerSliderCS;
	ofxFloatSlider powerSliderCF;

	float ppowerSliderCR = 0;
	float ppowerSliderCG = 0;
	float ppowerSliderCW = 0;
	float ppowerSliderCB = 0;
	float ppowerSliderCO = 0;
	float ppowerSliderCK = 0;
	float ppowerSliderCC = 0;
	float ppowerSliderCD = 0;
	float ppowerSliderCY = 0;
	float ppowerSliderCP = 0;
	float ppowerSliderCM = 0;
	float ppowerSliderCA = 0;
	float ppowerSliderCT = 0;
	float ppowerSliderCS = 0;
	float ppowerSliderCF = 0;

	ofxFloatSlider powerSliderDR;
	ofxFloatSlider powerSliderDG;
	ofxFloatSlider powerSliderDW;
	ofxFloatSlider powerSliderDB;
	ofxFloatSlider powerSliderDO;
	ofxFloatSlider powerSliderDK;
	ofxFloatSlider powerSliderDC;
	ofxFloatSlider powerSliderDD;
	ofxFloatSlider powerSliderDY;
	ofxFloatSlider powerSliderDP;
	ofxFloatSlider powerSliderDM;
	ofxFloatSlider powerSliderDA;
	ofxFloatSlider powerSliderDT;
	ofxFloatSlider powerSliderDS;
	ofxFloatSlider powerSliderDF;

	float ppowerSliderDR = 0;
	float ppowerSliderDG = 0;
	float ppowerSliderDW = 0;
	float ppowerSliderDB = 0;
	float ppowerSliderDO = 0;
	float ppowerSliderDK = 0;
	float ppowerSliderDC = 0;
	float ppowerSliderDD = 0;
	float ppowerSliderDY = 0;
	float ppowerSliderDP = 0;
	float ppowerSliderDM = 0;
	float ppowerSliderDA = 0;
	float ppowerSliderDT = 0;
	float ppowerSliderDS = 0;
	float ppowerSliderDF = 0;

	ofxFloatSlider powerSliderYR;
	ofxFloatSlider powerSliderYG;
	ofxFloatSlider powerSliderYW;
	ofxFloatSlider powerSliderYB;
	ofxFloatSlider powerSliderYO;
	ofxFloatSlider powerSliderYK;
	ofxFloatSlider powerSliderYC;
	ofxFloatSlider powerSliderYD;
	ofxFloatSlider powerSliderYY;
	ofxFloatSlider powerSliderYP;
	ofxFloatSlider powerSliderYM;
	ofxFloatSlider powerSliderYA;
	ofxFloatSlider powerSliderYT;
	ofxFloatSlider powerSliderYS;
	ofxFloatSlider powerSliderYF;

	float ppowerSliderYR = 0;
	float ppowerSliderYG = 0;
	float ppowerSliderYW = 0;
	float ppowerSliderYB = 0;
	float ppowerSliderYO = 0;
	float ppowerSliderYK = 0;
	float ppowerSliderYC = 0;
	float ppowerSliderYD = 0;
	float ppowerSliderYY = 0;
	float ppowerSliderYP = 0;
	float ppowerSliderYM = 0;
	float ppowerSliderYA = 0;
	float ppowerSliderYT = 0;
	float ppowerSliderYS = 0;
	float ppowerSliderYF = 0;

	ofxFloatSlider powerSliderPR;
	ofxFloatSlider powerSliderPG;
	ofxFloatSlider powerSliderPW;
	ofxFloatSlider powerSliderPB;
	ofxFloatSlider powerSliderPO;
	ofxFloatSlider powerSliderPK;
	ofxFloatSlider powerSliderPC;
	ofxFloatSlider powerSliderPD;
	ofxFloatSlider powerSliderPY;
	ofxFloatSlider powerSliderPP;
	ofxFloatSlider powerSliderPM;
	ofxFloatSlider powerSliderPA;
	ofxFloatSlider powerSliderPT;
	ofxFloatSlider powerSliderPS;
	ofxFloatSlider powerSliderPF;

	float ppowerSliderPR = 0;
	float ppowerSliderPG = 0;
	float ppowerSliderPW = 0;
	float ppowerSliderPB = 0;
	float ppowerSliderPO = 0;
	float ppowerSliderPK = 0;
	float ppowerSliderPC = 0;
	float ppowerSliderPD = 0;
	float ppowerSliderPY = 0;
	float ppowerSliderPP = 0;
	float ppowerSliderPM = 0;
	float ppowerSliderPA = 0;
	float ppowerSliderPT = 0;
	float ppowerSliderPS = 0;
	float ppowerSliderPF = 0;

	ofxFloatSlider powerSliderMR;
	ofxFloatSlider powerSliderMG;
	ofxFloatSlider powerSliderMW;
	ofxFloatSlider powerSliderMB;
	ofxFloatSlider powerSliderMO;
	ofxFloatSlider powerSliderMK;
	ofxFloatSlider powerSliderMC;
	ofxFloatSlider powerSliderMD;
	ofxFloatSlider powerSliderMY;
	ofxFloatSlider powerSliderMP;
	ofxFloatSlider powerSliderMM;
	ofxFloatSlider powerSliderMA;
	ofxFloatSlider powerSliderMT;
	ofxFloatSlider powerSliderMS;
	ofxFloatSlider powerSliderMF;

	float ppowerSliderMR = 0;
	float ppowerSliderMG = 0;
	float ppowerSliderMW = 0;
	float ppowerSliderMB = 0;
	float ppowerSliderMO = 0;
	float ppowerSliderMK = 0;
	float ppowerSliderMC = 0;
	float ppowerSliderMD = 0;
	float ppowerSliderMY = 0;
	float ppowerSliderMP = 0;
	float ppowerSliderMM = 0;
	float ppowerSliderMA = 0;
	float ppowerSliderMT = 0;
	float ppowerSliderMS = 0;
	float ppowerSliderMF = 0;

	ofxFloatSlider powerSliderAR;
	ofxFloatSlider powerSliderAG;
	ofxFloatSlider powerSliderAW;
	ofxFloatSlider powerSliderAB;
	ofxFloatSlider powerSliderAO;
	ofxFloatSlider powerSliderAK;
	ofxFloatSlider powerSliderAC;
	ofxFloatSlider powerSliderAD;
	ofxFloatSlider powerSliderAY;
	ofxFloatSlider powerSliderAP;
	ofxFloatSlider powerSliderAM;
	ofxFloatSlider powerSliderAA;
	ofxFloatSlider powerSliderAT;
	ofxFloatSlider powerSliderAS;
	ofxFloatSlider powerSliderAF;

	float ppowerSliderAR = 0;
	float ppowerSliderAG = 0;
	float ppowerSliderAW = 0;
	float ppowerSliderAB = 0;
	float ppowerSliderAO = 0;
	float ppowerSliderAK = 0;
	float ppowerSliderAC = 0;
	float ppowerSliderAD = 0;
	float ppowerSliderAY = 0;
	float ppowerSliderAP = 0;
	float ppowerSliderAM = 0;
	float ppowerSliderAA = 0;
	float ppowerSliderAT = 0;
	float ppowerSliderAS = 0;
	float ppowerSliderAF = 0;

	ofxFloatSlider powerSliderTR;
	ofxFloatSlider powerSliderTG;
	ofxFloatSlider powerSliderTW;
	ofxFloatSlider powerSliderTB;
	ofxFloatSlider powerSliderTO;
	ofxFloatSlider powerSliderTK;
	ofxFloatSlider powerSliderTC;
	ofxFloatSlider powerSliderTD;
	ofxFloatSlider powerSliderTY;
	ofxFloatSlider powerSliderTP;
	ofxFloatSlider powerSliderTM;
	ofxFloatSlider powerSliderTA;
	ofxFloatSlider powerSliderTT;
	ofxFloatSlider powerSliderTS;
	ofxFloatSlider powerSliderTF;

	float ppowerSliderTR = 0;
	float ppowerSliderTG = 0;
	float ppowerSliderTW = 0;
	float ppowerSliderTB = 0;
	float ppowerSliderTO = 0;
	float ppowerSliderTK = 0;
	float ppowerSliderTC = 0;
	float ppowerSliderTD = 0;
	float ppowerSliderTY = 0;
	float ppowerSliderTP = 0;
	float ppowerSliderTM = 0;
	float ppowerSliderTA = 0;
	float ppowerSliderTT = 0;
	float ppowerSliderTS = 0;
	float ppowerSliderTF = 0;

	ofxFloatSlider powerSliderSR;
	ofxFloatSlider powerSliderSG;
	ofxFloatSlider powerSliderSW;
	ofxFloatSlider powerSliderSB;
	ofxFloatSlider powerSliderSO;
	ofxFloatSlider powerSliderSK;
	ofxFloatSlider powerSliderSC;
	ofxFloatSlider powerSliderSD;
	ofxFloatSlider powerSliderSY;
	ofxFloatSlider powerSliderSP;
	ofxFloatSlider powerSliderSM;
	ofxFloatSlider powerSliderSA;
	ofxFloatSlider powerSliderST;
	ofxFloatSlider powerSliderSS;
	ofxFloatSlider powerSliderSF;

	float ppowerSliderSR = 0;
	float ppowerSliderSG = 0;
	float ppowerSliderSW = 0;
	float ppowerSliderSB = 0;
	float ppowerSliderSO = 0;
	float ppowerSliderSK = 0;
	float ppowerSliderSC = 0;
	float ppowerSliderSD = 0;
	float ppowerSliderSY = 0;
	float ppowerSliderSP = 0;
	float ppowerSliderSM = 0;
	float ppowerSliderSA = 0;
	float ppowerSliderST = 0;
	float ppowerSliderSS = 0;
	float ppowerSliderSF = 0;

	ofxFloatSlider powerSliderFR;
	ofxFloatSlider powerSliderFG;
	ofxFloatSlider powerSliderFW;
	ofxFloatSlider powerSliderFB;
	ofxFloatSlider powerSliderFO;
	ofxFloatSlider powerSliderFK;
	ofxFloatSlider powerSliderFC;
	ofxFloatSlider powerSliderFD;
	ofxFloatSlider powerSliderFY;
	ofxFloatSlider powerSliderFP;
	ofxFloatSlider powerSliderFM;
	ofxFloatSlider powerSliderFA;
	ofxFloatSlider powerSliderFT;
	ofxFloatSlider powerSliderFS;
	ofxFloatSlider powerSliderFF;

	float ppowerSliderFR = 0;
	float ppowerSliderFG = 0;
	float ppowerSliderFW = 0;
	float ppowerSliderFB = 0;
	float ppowerSliderFO = 0;
	float ppowerSliderFK = 0;
	float ppowerSliderFC = 0;
	float ppowerSliderFD = 0;
	float ppowerSliderFY = 0;
	float ppowerSliderFP = 0;
	float ppowerSliderFM = 0;
	float ppowerSliderFA = 0;
	float ppowerSliderFT = 0;
	float ppowerSliderFS = 0;
	float ppowerSliderFF = 0;

	ofxFloatSlider vSliderRR;
	ofxFloatSlider vSliderRG;
	ofxFloatSlider vSliderRW;
	ofxFloatSlider vSliderRB;
	ofxFloatSlider vSliderRO;
	ofxFloatSlider vSliderRK;
	ofxFloatSlider vSliderRC;
	ofxFloatSlider vSliderRD;
	ofxFloatSlider vSliderRY;
	ofxFloatSlider vSliderRP;
	ofxFloatSlider vSliderRM;
	ofxFloatSlider vSliderRA;
	ofxFloatSlider vSliderRT;
	ofxFloatSlider vSliderRS;
	ofxFloatSlider vSliderRF;

	float pvSliderRR = 0;
	float pvSliderRG = 0;
	float pvSliderRW = 0;
	float pvSliderRB = 0;
	float pvSliderRO = 0;
	float pvSliderRK = 0;
	float pvSliderRC = 0;
	float pvSliderRD = 0;
	float pvSliderRY = 0;
	float pvSliderRP = 0;
	float pvSliderRM = 0;
	float pvSliderRA = 0;
	float pvSliderRT = 0;
	float pvSliderRS = 0;
	float pvSliderRF = 0;

	ofxFloatSlider vSliderGR;
	ofxFloatSlider vSliderGG;
	ofxFloatSlider vSliderGW;
	ofxFloatSlider vSliderGB;
	ofxFloatSlider vSliderGO;
	ofxFloatSlider vSliderGK;
	ofxFloatSlider vSliderGC;
	ofxFloatSlider vSliderGD;
	ofxFloatSlider vSliderGY;
	ofxFloatSlider vSliderGP;
	ofxFloatSlider vSliderGM;
	ofxFloatSlider vSliderGA;
	ofxFloatSlider vSliderGT;
	ofxFloatSlider vSliderGS;
	ofxFloatSlider vSliderGF;

	float pvSliderGR = 0;
	float pvSliderGG = 0;
	float pvSliderGW = 0;
	float pvSliderGB = 0;
	float pvSliderGO = 0;
	float pvSliderGK = 0;
	float pvSliderGC = 0;
	float pvSliderGD = 0;
	float pvSliderGY = 0;
	float pvSliderGP = 0;
	float pvSliderGM = 0;
	float pvSliderGA = 0;
	float pvSliderGT = 0;
	float pvSliderGS = 0;
	float pvSliderGF = 0;

	ofxFloatSlider vSliderWR;
	ofxFloatSlider vSliderWG;
	ofxFloatSlider vSliderWW;
	ofxFloatSlider vSliderWB;
	ofxFloatSlider vSliderWO;
	ofxFloatSlider vSliderWK;
	ofxFloatSlider vSliderWC;
	ofxFloatSlider vSliderWD;
	ofxFloatSlider vSliderWY;
	ofxFloatSlider vSliderWP;
	ofxFloatSlider vSliderWM;
	ofxFloatSlider vSliderWA;
	ofxFloatSlider vSliderWT;
	ofxFloatSlider vSliderWS;
	ofxFloatSlider vSliderWF;

	float pvSliderWR = 0;
	float pvSliderWG = 0;
	float pvSliderWW = 0;
	float pvSliderWB = 0;
	float pvSliderWO = 0;
	float pvSliderWK = 0;
	float pvSliderWC = 0;
	float pvSliderWD = 0;
	float pvSliderWY = 0;
	float pvSliderWP = 0;
	float pvSliderWM = 0;
	float pvSliderWA = 0;
	float pvSliderWT = 0;
	float pvSliderWS = 0;
	float pvSliderWF = 0;

	ofxFloatSlider vSliderBR;
	ofxFloatSlider vSliderBG;
	ofxFloatSlider vSliderBW;
	ofxFloatSlider vSliderBB;
	ofxFloatSlider vSliderBO;
	ofxFloatSlider vSliderBK;
	ofxFloatSlider vSliderBC;
	ofxFloatSlider vSliderBD;
	ofxFloatSlider vSliderBY;
	ofxFloatSlider vSliderBP;
	ofxFloatSlider vSliderBM;
	ofxFloatSlider vSliderBA;
	ofxFloatSlider vSliderBT;
	ofxFloatSlider vSliderBS;
	ofxFloatSlider vSliderBF;

	float pvSliderBR = 0;
	float pvSliderBG = 0;
	float pvSliderBW = 0;
	float pvSliderBB = 0;
	float pvSliderBO = 0;
	float pvSliderBK = 0;
	float pvSliderBC = 0;
	float pvSliderBD = 0;
	float pvSliderBY = 0;
	float pvSliderBP = 0;
	float pvSliderBM = 0;
	float pvSliderBA = 0;
	float pvSliderBT = 0;
	float pvSliderBS = 0;
	float pvSliderBF = 0;

	ofxFloatSlider vSliderOR;
	ofxFloatSlider vSliderOG;
	ofxFloatSlider vSliderOW;
	ofxFloatSlider vSliderOB;
	ofxFloatSlider vSliderOO;
	ofxFloatSlider vSliderOK;
	ofxFloatSlider vSliderOC;
	ofxFloatSlider vSliderOD;
	ofxFloatSlider vSliderOY;
	ofxFloatSlider vSliderOP;
	ofxFloatSlider vSliderOM;
	ofxFloatSlider vSliderOA;
	ofxFloatSlider vSliderOT;
	ofxFloatSlider vSliderOS;
	ofxFloatSlider vSliderOF;

	float pvSliderOR = 0;
	float pvSliderOG = 0;
	float pvSliderOW = 0;
	float pvSliderOB = 0;
	float pvSliderOO = 0;
	float pvSliderOK = 0;
	float pvSliderOC = 0;
	float pvSliderOD = 0;
	float pvSliderOY = 0;
	float pvSliderOP = 0;
	float pvSliderOM = 0;
	float pvSliderOA = 0;
	float pvSliderOT = 0;
	float pvSliderOS = 0;
	float pvSliderOF = 0;

	ofxFloatSlider vSliderKR;
	ofxFloatSlider vSliderKG;
	ofxFloatSlider vSliderKW;
	ofxFloatSlider vSliderKB;
	ofxFloatSlider vSliderKO;
	ofxFloatSlider vSliderKK;
	ofxFloatSlider vSliderKC;
	ofxFloatSlider vSliderKD;
	ofxFloatSlider vSliderKY;
	ofxFloatSlider vSliderKP;
	ofxFloatSlider vSliderKM;
	ofxFloatSlider vSliderKA;
	ofxFloatSlider vSliderKT;
	ofxFloatSlider vSliderKS;
	ofxFloatSlider vSliderKF;

	float pvSliderKR = 0;
	float pvSliderKG = 0;
	float pvSliderKW = 0;
	float pvSliderKB = 0;
	float pvSliderKO = 0;
	float pvSliderKK = 0;
	float pvSliderKC = 0;
	float pvSliderKD = 0;
	float pvSliderKY = 0;
	float pvSliderKP = 0;
	float pvSliderKM = 0;
	float pvSliderKA = 0;
	float pvSliderKT = 0;
	float pvSliderKS = 0;
	float pvSliderKF = 0;

	ofxFloatSlider vSliderCR;
	ofxFloatSlider vSliderCG;
	ofxFloatSlider vSliderCW;
	ofxFloatSlider vSliderCB;
	ofxFloatSlider vSliderCO;
	ofxFloatSlider vSliderCK;
	ofxFloatSlider vSliderCC;
	ofxFloatSlider vSliderCD;
	ofxFloatSlider vSliderCY;
	ofxFloatSlider vSliderCP;
	ofxFloatSlider vSliderCM;
	ofxFloatSlider vSliderCA;
	ofxFloatSlider vSliderCT;
	ofxFloatSlider vSliderCS;
	ofxFloatSlider vSliderCF;

	float pvSliderCR = 0;
	float pvSliderCG = 0;
	float pvSliderCW = 0;
	float pvSliderCB = 0;
	float pvSliderCO = 0;
	float pvSliderCK = 0;
	float pvSliderCC = 0;
	float pvSliderCD = 0;
	float pvSliderCY = 0;
	float pvSliderCP = 0;
	float pvSliderCM = 0;
	float pvSliderCA = 0;
	float pvSliderCT = 0;
	float pvSliderCS = 0;
	float pvSliderCF = 0;

	ofxFloatSlider vSliderDR;
	ofxFloatSlider vSliderDG;
	ofxFloatSlider vSliderDW;
	ofxFloatSlider vSliderDB;
	ofxFloatSlider vSliderDO;
	ofxFloatSlider vSliderDK;
	ofxFloatSlider vSliderDC;
	ofxFloatSlider vSliderDD;
	ofxFloatSlider vSliderDY;
	ofxFloatSlider vSliderDP;
	ofxFloatSlider vSliderDM;
	ofxFloatSlider vSliderDA;
	ofxFloatSlider vSliderDT;
	ofxFloatSlider vSliderDS;
	ofxFloatSlider vSliderDF;

	float pvSliderDR = 0;
	float pvSliderDG = 0;
	float pvSliderDW = 0;
	float pvSliderDB = 0;
	float pvSliderDO = 0;
	float pvSliderDK = 0;
	float pvSliderDC = 0;
	float pvSliderDD = 0;
	float pvSliderDY = 0;
	float pvSliderDP = 0;
	float pvSliderDM = 0;
	float pvSliderDA = 0;
	float pvSliderDT = 0;
	float pvSliderDS = 0;
	float pvSliderDF = 0;

	ofxFloatSlider vSliderYR;
	ofxFloatSlider vSliderYG;
	ofxFloatSlider vSliderYW;
	ofxFloatSlider vSliderYB;
	ofxFloatSlider vSliderYO;
	ofxFloatSlider vSliderYK;
	ofxFloatSlider vSliderYC;
	ofxFloatSlider vSliderYD;
	ofxFloatSlider vSliderYY;
	ofxFloatSlider vSliderYP;
	ofxFloatSlider vSliderYM;
	ofxFloatSlider vSliderYA;
	ofxFloatSlider vSliderYT;
	ofxFloatSlider vSliderYS;
	ofxFloatSlider vSliderYF;

	float pvSliderYR = 0;
	float pvSliderYG = 0;
	float pvSliderYW = 0;
	float pvSliderYB = 0;
	float pvSliderYO = 0;
	float pvSliderYK = 0;
	float pvSliderYC = 0;
	float pvSliderYD = 0;
	float pvSliderYY = 0;
	float pvSliderYP = 0;
	float pvSliderYM = 0;
	float pvSliderYA = 0;
	float pvSliderYT = 0;
	float pvSliderYS = 0;
	float pvSliderYF = 0;

	ofxFloatSlider vSliderPR;
	ofxFloatSlider vSliderPG;
	ofxFloatSlider vSliderPW;
	ofxFloatSlider vSliderPB;
	ofxFloatSlider vSliderPO;
	ofxFloatSlider vSliderPK;
	ofxFloatSlider vSliderPC;
	ofxFloatSlider vSliderPD;
	ofxFloatSlider vSliderPY;
	ofxFloatSlider vSliderPP;
	ofxFloatSlider vSliderPM;
	ofxFloatSlider vSliderPA;
	ofxFloatSlider vSliderPT;
	ofxFloatSlider vSliderPS;
	ofxFloatSlider vSliderPF;

	float pvSliderPR = 0;
	float pvSliderPG = 0;
	float pvSliderPW = 0;
	float pvSliderPB = 0;
	float pvSliderPO = 0;
	float pvSliderPK = 0;
	float pvSliderPC = 0;
	float pvSliderPD = 0;
	float pvSliderPY = 0;
	float pvSliderPP = 0;
	float pvSliderPM = 0;
	float pvSliderPA = 0;
	float pvSliderPT = 0;
	float pvSliderPS = 0;
	float pvSliderPF = 0;

	ofxFloatSlider vSliderMR;
	ofxFloatSlider vSliderMG;
	ofxFloatSlider vSliderMW;
	ofxFloatSlider vSliderMB;
	ofxFloatSlider vSliderMO;
	ofxFloatSlider vSliderMK;
	ofxFloatSlider vSliderMC;
	ofxFloatSlider vSliderMD;
	ofxFloatSlider vSliderMY;
	ofxFloatSlider vSliderMP;
	ofxFloatSlider vSliderMM;
	ofxFloatSlider vSliderMA;
	ofxFloatSlider vSliderMT;
	ofxFloatSlider vSliderMS;
	ofxFloatSlider vSliderMF;

	float pvSliderMR = 0;
	float pvSliderMG = 0;
	float pvSliderMW = 0;
	float pvSliderMB = 0;
	float pvSliderMO = 0;
	float pvSliderMK = 0;
	float pvSliderMC = 0;
	float pvSliderMD = 0;
	float pvSliderMY = 0;
	float pvSliderMP = 0;
	float pvSliderMM = 0;
	float pvSliderMA = 0;
	float pvSliderMT = 0;
	float pvSliderMS = 0;
	float pvSliderMF = 0;

	ofxFloatSlider vSliderAR;
	ofxFloatSlider vSliderAG;
	ofxFloatSlider vSliderAW;
	ofxFloatSlider vSliderAB;
	ofxFloatSlider vSliderAO;
	ofxFloatSlider vSliderAK;
	ofxFloatSlider vSliderAC;
	ofxFloatSlider vSliderAD;
	ofxFloatSlider vSliderAY;
	ofxFloatSlider vSliderAP;
	ofxFloatSlider vSliderAM;
	ofxFloatSlider vSliderAA;
	ofxFloatSlider vSliderAT;
	ofxFloatSlider vSliderAS;
	ofxFloatSlider vSliderAF;

	float pvSliderAR = 0;
	float pvSliderAG = 0;
	float pvSliderAW = 0;
	float pvSliderAB = 0;
	float pvSliderAO = 0;
	float pvSliderAK = 0;
	float pvSliderAC = 0;
	float pvSliderAD = 0;
	float pvSliderAY = 0;
	float pvSliderAP = 0;
	float pvSliderAM = 0;
	float pvSliderAA = 0;
	float pvSliderAT = 0;
	float pvSliderAS = 0;
	float pvSliderAF = 0;

	ofxFloatSlider vSliderTR;
	ofxFloatSlider vSliderTG;
	ofxFloatSlider vSliderTW;
	ofxFloatSlider vSliderTB;
	ofxFloatSlider vSliderTO;
	ofxFloatSlider vSliderTK;
	ofxFloatSlider vSliderTC;
	ofxFloatSlider vSliderTD;
	ofxFloatSlider vSliderTY;
	ofxFloatSlider vSliderTP;
	ofxFloatSlider vSliderTM;
	ofxFloatSlider vSliderTA;
	ofxFloatSlider vSliderTT;
	ofxFloatSlider vSliderTS;
	ofxFloatSlider vSliderTF;

	float pvSliderTR = 0;
	float pvSliderTG = 0;
	float pvSliderTW = 0;
	float pvSliderTB = 0;
	float pvSliderTO = 0;
	float pvSliderTK = 0;
	float pvSliderTC = 0;
	float pvSliderTD = 0;
	float pvSliderTY = 0;
	float pvSliderTP = 0;
	float pvSliderTM = 0;
	float pvSliderTA = 0;
	float pvSliderTT = 0;
	float pvSliderTS = 0;
	float pvSliderTF = 0;

	ofxFloatSlider vSliderSR;
	ofxFloatSlider vSliderSG;
	ofxFloatSlider vSliderSW;
	ofxFloatSlider vSliderSB;
	ofxFloatSlider vSliderSO;
	ofxFloatSlider vSliderSK;
	ofxFloatSlider vSliderSC;
	ofxFloatSlider vSliderSD;
	ofxFloatSlider vSliderSY;
	ofxFloatSlider vSliderSP;
	ofxFloatSlider vSliderSM;
	ofxFloatSlider vSliderSA;
	ofxFloatSlider vSliderST;
	ofxFloatSlider vSliderSS;
	ofxFloatSlider vSliderSF;

	float pvSliderSR = 0;
	float pvSliderSG = 0;
	float pvSliderSW = 0;
	float pvSliderSB = 0;
	float pvSliderSO = 0;
	float pvSliderSK = 0;
	float pvSliderSC = 0;
	float pvSliderSD = 0;
	float pvSliderSY = 0;
	float pvSliderSP = 0;
	float pvSliderSM = 0;
	float pvSliderSA = 0;
	float pvSliderST = 0;
	float pvSliderSS = 0;
	float pvSliderSF = 0;

	ofxFloatSlider vSliderFR;
	ofxFloatSlider vSliderFG;
	ofxFloatSlider vSliderFW;
	ofxFloatSlider vSliderFB;
	ofxFloatSlider vSliderFO;
	ofxFloatSlider vSliderFK;
	ofxFloatSlider vSliderFC;
	ofxFloatSlider vSliderFD;
	ofxFloatSlider vSliderFY;
	ofxFloatSlider vSliderFP;
	ofxFloatSlider vSliderFM;
	ofxFloatSlider vSliderFA;
	ofxFloatSlider vSliderFT;
	ofxFloatSlider vSliderFS;
	ofxFloatSlider vSliderFF;

	float pvSliderFR = 0;
	float pvSliderFG = 0;
	float pvSliderFW = 0;
	float pvSliderFB = 0;
	float pvSliderFO = 0;
	float pvSliderFK = 0;
	float pvSliderFC = 0;
	float pvSliderFD = 0;
	float pvSliderFY = 0;
	float pvSliderFP = 0;
	float pvSliderFM = 0;
	float pvSliderFA = 0;
	float pvSliderFT = 0;
	float pvSliderFS = 0;
	float pvSliderFF = 0;

	ofxLabel labelG;
	ofxLabel labelR;
	ofxLabel labelW;
	ofxLabel labelB;
	ofxLabel labelO;
	ofxLabel labelK;
	ofxLabel labelC;
	ofxLabel labelD;
	ofxLabel labelY;
	ofxLabel labelP;
	ofxLabel labelM;
	ofxLabel labelA;
	ofxLabel labelT;
	ofxLabel labelS;
	ofxLabel labelF;
	ofxLabel aboutL1;
	ofxLabel aboutL2;
	ofxLabel aboutL3;
	ofxLabel fps;

	// simulation bounds
	int boundWidth = 1600;
	int boundHeight = 900;

	float viscosity = 0.5F;

	float viscosityRR = 0.2F;
	float viscosityRG = 0.3F;
	float viscosityRW = 0.4F;
	float viscosityRB = 0.5F;
	float viscosityRO = 0.6F;
	float viscosityRK = 0.7F;
	float viscosityRC = 0.8F;
	float viscosityRD = 0.9F;
	float viscosityRY = 0.3F;
	float viscosityRP = 0.4F;
	float viscosityRM = 0.5F;
	float viscosityRA = 0.6F;
	float viscosityRT = 0.7F;
	float viscosityRS = 0.8F;
	float viscosityRF = 0.9F;

	float viscosityGR = 0.3F;
	float viscosityGG = 0.4F;
	float viscosityGW = 0.5F;
	float viscosityGB = 0.6F;
	float viscosityGO = 0.7F;
	float viscosityGK = 0.8F;
	float viscosityGC = 0.9F;
	float viscosityGD = 0.2F;
	float viscosityGY = 0.4F;
	float viscosityGP = 0.5F;
	float viscosityGM = 0.6F;
	float viscosityGA = 0.7F;
	float viscosityGT = 0.8F;
	float viscosityGS = 0.9F;
	float viscosityGF = 0.2F;

	float viscosityBR = 0.4F;
	float viscosityBG = 0.5F;
	float viscosityBW = 0.6F;
	float viscosityBB = 0.7F;
	float viscosityBO = 0.8F;
	float viscosityBK = 0.9F;
	float viscosityBC = 0.2F;
	float viscosityBD = 0.3F;
	float viscosityBY = 0.5F;
	float viscosityBP = 0.6F;
	float viscosityBM = 0.7F;
	float viscosityBA = 0.8F;
	float viscosityBT = 0.9F;
	float viscosityBS = 0.2F;
	float viscosityBF = 0.3F;

	float viscosityWR = 0.5F;
	float viscosityWG = 0.6F;
	float viscosityWW = 0.7F;
	float viscosityWB = 0.8F;
	float viscosityWO = 0.9F;
	float viscosityWK = 0.2F;
	float viscosityWC = 0.3F;
	float viscosityWD = 0.4F;
	float viscosityWY = 0.6F;
	float viscosityWP = 0.7F;
	float viscosityWM = 0.8F;
	float viscosityWA = 0.9F;
	float viscosityWT = 0.2F;
	float viscosityWS = 0.3F;
	float viscosityWF = 0.4F;

	float viscosityOR = 0.6F;
	float viscosityOG = 0.7F;
	float viscosityOW = 0.8F;
	float viscosityOB = 0.9F;
	float viscosityOO = 0.2F;
	float viscosityOK = 0.3F;
	float viscosityOC = 0.4F;
	float viscosityOD = 0.5F;
	float viscosityOY = 0.7F;
	float viscosityOP = 0.8F;
	float viscosityOM = 0.9F;
	float viscosityOA = 0.2F;
	float viscosityOT = 0.3F;
	float viscosityOS = 0.4F;
	float viscosityOF = 0.5F;

	float viscosityKR = 0.7F;
	float viscosityKG = 0.8F;
	float viscosityKW = 0.9F;
	float viscosityKB = 0.2F;
	float viscosityKO = 0.3F;
	float viscosityKK = 0.4F;
	float viscosityKC = 0.5F;
	float viscosityKD = 0.6F;
	float viscosityKY = 0.8F;
	float viscosityKP = 0.9F;
	float viscosityKM = 0.2F;
	float viscosityKA = 0.3F;
	float viscosityKT = 0.4F;
	float viscosityKS = 0.5F;
	float viscosityKF = 0.6F;

	float viscosityCR = 0.8F;
	float viscosityCG = 0.9F;
	float viscosityCW = 0.2F;
	float viscosityCB = 0.3F;
	float viscosityCO = 0.4F;
	float viscosityCK = 0.5F;
	float viscosityCC = 0.6F;
	float viscosityCD = 0.7F;
	float viscosityCY = 0.9F;
	float viscosityCP = 0.2F;
	float viscosityCM = 0.3F;
	float viscosityCA = 0.4F;
	float viscosityCT = 0.5F;
	float viscosityCS = 0.6F;
	float viscosityCF = 0.7F;

	float viscosityDR = 0.9F;
	float viscosityDG = 0.2F;
	float viscosityDW = 0.3F;
	float viscosityDB = 0.4F;
	float viscosityDO = 0.5F;
	float viscosityDK = 0.6F;
	float viscosityDC = 0.7F;
	float viscosityDD = 0.8F;
	float viscosityDY = 0.2F;
	float viscosityDP = 0.3F;
	float viscosityDM = 0.4F;
	float viscosityDA = 0.5F;
	float viscosityDT = 0.6F;
	float viscosityDS = 0.7F;
	float viscosityDF = 0.8F;

	float viscosityYR = 0.9F;
	float viscosityYG = 0.2F;
	float viscosityYW = 0.3F;
	float viscosityYB = 0.4F;
	float viscosityYO = 0.5F;
	float viscosityYK = 0.6F;
	float viscosityYC = 0.7F;
	float viscosityYD = 0.8F;
	float viscosityYY = 0.2F;
	float viscosityYP = 0.3F;
	float viscosityYM = 0.4F;
	float viscosityYA = 0.5F;
	float viscosityYT = 0.6F;
	float viscosityYS = 0.7F;
	float viscosityYF = 0.8F;

	float viscosityPR = 0.9F;
	float viscosityPG = 0.2F;
	float viscosityPW = 0.3F;
	float viscosityPB = 0.4F;
	float viscosityPO = 0.5F;
	float viscosityPK = 0.6F;
	float viscosityPC = 0.7F;
	float viscosityPD = 0.8F;
	float viscosityPY = 0.2F;
	float viscosityPP = 0.3F;
	float viscosityPM = 0.4F;
	float viscosityPA = 0.5F;
	float viscosityPT = 0.6F;
	float viscosityPS = 0.7F;
	float viscosityPF = 0.8F;

	float viscosityMR = 0.9F;
	float viscosityMG = 0.2F;
	float viscosityMW = 0.3F;
	float viscosityMB = 0.4F;
	float viscosityMO = 0.5F;
	float viscosityMK = 0.6F;
	float viscosityMC = 0.7F;
	float viscosityMD = 0.8F;
	float viscosityMY = 0.2F;
	float viscosityMP = 0.3F;
	float viscosityMM = 0.4F;
	float viscosityMA = 0.5F;
	float viscosityMT = 0.6F;
	float viscosityMS = 0.7F;
	float viscosityMF = 0.8F;

	float viscosityAR = 0.9F;
	float viscosityAG = 0.2F;
	float viscosityAW = 0.3F;
	float viscosityAB = 0.4F;
	float viscosityAO = 0.5F;
	float viscosityAK = 0.6F;
	float viscosityAC = 0.7F;
	float viscosityAD = 0.8F;
	float viscosityAY = 0.2F;
	float viscosityAP = 0.3F;
	float viscosityAM = 0.4F;
	float viscosityAA = 0.5F;
	float viscosityAT = 0.6F;
	float viscosityAS = 0.7F;
	float viscosityAF = 0.8F;

	float viscosityTR = 0.9F;
	float viscosityTG = 0.2F;
	float viscosityTW = 0.3F;
	float viscosityTB = 0.4F;
	float viscosityTO = 0.5F;
	float viscosityTK = 0.6F;
	float viscosityTC = 0.7F;
	float viscosityTD = 0.8F;
	float viscosityTY = 0.2F;
	float viscosityTP = 0.3F;
	float viscosityTM = 0.4F;
	float viscosityTA = 0.5F;
	float viscosityTT = 0.6F;
	float viscosityTS = 0.7F;
	float viscosityTF = 0.8F;

	float viscositySR = 0.9F;
	float viscositySG = 0.2F;
	float viscositySW = 0.3F;
	float viscositySB = 0.4F;
	float viscositySO = 0.5F;
	float viscositySK = 0.6F;
	float viscositySC = 0.7F;
	float viscositySD = 0.8F;
	float viscositySY = 0.2F;
	float viscositySP = 0.3F;
	float viscositySM = 0.4F;
	float viscositySA = 0.5F;
	float viscosityST = 0.6F;
	float viscositySS = 0.7F;
	float viscositySF = 0.8F;

	float viscosityFR = 0.9F;
	float viscosityFG = 0.2F;
	float viscosityFW = 0.3F;
	float viscosityFB = 0.4F;
	float viscosityFO = 0.5F;
	float viscosityFK = 0.6F;
	float viscosityFC = 0.7F;
	float viscosityFD = 0.8F;
	float viscosityFY = 0.2F;
	float viscosityFP = 0.3F;
	float viscosityFM = 0.4F;
	float viscosityFA = 0.5F;
	float viscosityFT = 0.6F;
	float viscosityFS = 0.7F;
	float viscosityFF = 0.8F;

	float worldGravity = 0.0F;
	float forceVariance = 0.7F;
	float radiusVariance = 0.5F;
	float wallRepel = 20.0F;
};
